from graphviz import Digraph
from ArbolBinario import ArbolBinario
from ListaDoble import ListaDoble
from MatrizDispersa import MatrizDispersa

ab=ArbolBinario()
ld=ListaDoble()
md=MatrizDispersa()
ab.Insertar("hola","1",0)
ab.Insertar("hace","2",1)
ab.Insertar("qie","3",1)
ab.Insertar("dece","4",1)
ab.Insertar("dedos","5",1)
ab.Insertar("dama","6",1)
ab.Insertar("cca","7",0)
ab.Insertar("cafe","8",0)

ab.CrearReporte()
print("Preorden")
ab.MostrarPreorden(ab.DameRaiz())
print("Postorden")
ab.MostrarPostorden(ab.DameRaiz())
print("Inorden")
ab.MostrarInorden(ab.DameRaiz())
#print("Despues de Eliminar un nodo")
#ab.Eliminar(ab.BuscarNodo("bb"))
#print("Preorden")
#ab.MostrarPreorden(ab.DameRaiz())
#print("Postorden")
#ab.MostrarPostorden(ab.DameRaiz())
#print("Inorden")
#ab.MostrarInorden(ab.DameRaiz())
#ab.Modificar(ab.BuscarNodo("ddd"),"jaja","si",0)

#print("Preorden")
#ab.MostrarPreorden(ab.DameRaiz())
#print("Postorden")
#ab.MostrarPostorden(ab.DameRaiz())
#print("Inorden")
#ab.MostrarInorden(ab.DameRaiz())
print("Lista doble enlazada")
ld.InsertarPrimero("j1","j2","","","","","")
ld.InsertarPrimero("j2","j1","","","","","")
ld.InsertarPrimero("jamejameja","jamejameja","","","","","")
ld.InsertarPrimero("Luis","Luis","","","","","")
ld.InsertarPrimero("Joel","Joel","","","","","")
ld.MostrarPrimeroUltimo()
ld.MostrarUltimoPrimero()
ld.Graficar()
print("Matriz Dispersa...")
#ab.CrearReporte()
md.CrearMatriz(8,8)
print("Matriz creada")
md.InsertarMatriz("a",1,3)
#md.InsertarMatriz(5,1,4)
#avion 1
md.InsertarMatriz("a",3,2)
md.InsertarMatriz("a", 1, 1)
md.InsertarMatriz("a", 1, 2)
md.InsertarMatriz("a", 2, 2)
#md.InsertarMatriz("a", 4, 2)
#avion 2
#md.InsertarMatriz("b",4,3)
#md.InsertarMatriz("b",4,4)
md.InsertarMatriz("a",4,5)
md.InsertarMatriz("a", 4, 2)

md.InsertarMatriz("a",4,6)
md.InsertarMatriz("a",5,6)
md.InsertarMatriz("a",6,6)
md.InsertarMatriz("z",8,5)
md.InsertarMatriz("z",8,3)
md.InsertarMatriz("z", 8, 1)
md.Imprimir(md.m)
md.Nivel1=MatrizDispersa()
md.Nivel2=MatrizDispersa()
md.Nivel3=MatrizDispersa()
md.Nivel4=MatrizDispersa()
md.Nivel1.CrearMatriz(8,8)
md.Nivel2.CrearMatriz(8,8)
md.Nivel3.CrearMatriz(8,8)
md.Nivel4.CrearMatriz(8,8)
md.Insertar("D",4,1,0,0)
md.Insertar("H",8,1,0,0)
print("Satelites")
md.Nivel1.Imprimir(md.Nivel1.m)
print("-----------------------------------------------------------------------------")
md.Insertar("B",1,2,1,0)
md.Insertar("E",4,2,2,0)
print("Aviones")
md.Nivel2.Imprimir(md.Nivel2.m)
print("-----------------------------------------------------------------------------")
md.Insertar("C",3,3,1,1)
md.Insertar("G",8,3,2,2)
md.Insertar("E",6,3,3,1)
print("Barcos")
md.Nivel3.Imprimir(md.Nivel3.m)
print("-----------------------------------------------------------------------------")
md.Insertar("C",3,4,1,1)
md.Insertar("F",1,4,2,2)
md.Insertar("E",6,4,3,1)
print("Submarinos")
md.Nivel4.Imprimir(md.Nivel4.m)
print("-----------------------------------------------------------------------------")

#md.InsertarMatriz(8, 4, 3)
#md.InsertarMatriz(6, 2, 3)

#myDict = {'a':1,'b':2,'c':3,'d':4}
#print(myDict)
#keys=myDict.keys()
#print keys
